site_name: Django tracker
site_url: https://tijani-dia.github.io/django-tracker/
repo_url: https://github.com/tijani-dia/django-tracker
repo_name: tijani-dia/django-tracker
theme:
  name: material
  palette:
    primary: blue grey

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
