name: Documentation

on:
  push:
    branches:
      - main
    # Only deploy when the relevant files have changed
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install '.[docs]'
        env:
          SKIP_TAILWIND: true

      - name: Build & deploy documentation
        run: |
          # Assume the identity of the github actions bot
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
          mkdocs gh-deploy --force
